services:
  box-newking:
    build:
      context: ..
      dockerfile: backend/Dockerfile
      args:
        APP_VERSION: "2.5.4"
        VCS_REF: "local"
    image: box-newking:local
    container_name: box-newking
    volumes:
      - box-newking-data:/app/data:rw
    restart: unless-stopped
    ports:
      - "12345:12345"

volumes:
  box-newking-data:
    external: false
